apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "f5xc-rp-tunnel.fullname" . }}
  labels:
    {{- include "f5xc-rp-tunnel.labels" . | nindent 4 }}
data:
    {{- with .Values.environment }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  