{{- if .Values.authorizedKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: authorizedkeys
  labels:
    {{- include "f5xc-rp-tunnel.labels" . | nindent 4 }}
type: Opaque
data:
  authorized_keys: {{ .Values.authorizedKeys | b64enc }}
{{- end}}