apiVersion: v1
kind: Service
metadata:
  name: {{ include "f5xc-rp-tunnel.fullname" . }}
  labels:
    {{- include "f5xc-rp-tunnel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.servicePorts }}
  ports:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "f5xc-rp-tunnel.selectorLabels" . | nindent 4 }}
