apiVersion: v1
kind: Secret
metadata:
  name: {{ include "f5xc-frps.fullname" . }}
  labels:
    {{- include "f5xc-frps.labels" . | nindent 4 }}
type: Opaque
data:
  caCert: {{ .Values.caCert | b64enc }}
  serverCert: {{ .Values.serverCert | b64enc }}
  serverKey: {{ .Values.serverKey | b64enc }}
