apiVersion: v1
kind: Service
metadata:
  name: {{ include "f5xc-frps.fullname" . }}
  labels:
    {{- include "f5xc-frps.labels" . | nindent 4 }}
spec:
  ports:
    - name: "control"
      port: {{ .Values.bindPort }}
      targetPort: {{ .Values.bindPort }}
    - name: "http"
      port: {{ .Values.vhostHTTPPort }}
      targetPort: {{ .Values.vhostHTTPPort }}
    - name: "https"
      port: {{ .Values.vhostHTTPSPort }}
      targetPort: {{ .Values.vhostHTTPSPort }}
  selector:
    {{- include "f5xc-frps.selectorLabels" . | nindent 4 }}